name: PunishmentGUI
version: 1.0.3
description: Gives a GUI window to punish players
author: Chiller
main: me.chiller.punishmentgui.core.Main
commands:
  punish:
    description: 'Punishes the given player'
    usage: '§c§lPUNISH §r§6Do /punish <PlayerName> <Reason>'
    aliases: p
    permission: 'punishment.use'
    permission-message: ''
permissions:
  punish.use:
    description: 'Gives the ability to use the punish GUI'
  punish.temp_mute:
    description: 'Gives the ability to temp mute a player in the GUI'
  punish.temp_ban:
    description: 'Gives the ability to temp ban a player in the GUI'
  punish.perm_ban:
    description: 'Gives the ability to perm ban a player in the GUI'
  punish.perm_mute:
    description: 'Gives the ability to perm mute a player in the GUI'