name: PunishmentGUI
version: 0.1
description: Gives a GUI window to punish players
author: Tecno_Wizard
main: com.tecno_wizard.plugingui.core.Main
commands:
  punish:
    description: 'Staff command used to punish a player'
    usage: '§c§lERROR §6Incorrect usage. /punish (Player) (Reason)'
    permission: 'punishment.use'
    permission-message: '
permissions:
